apiVersion: apps/v1
kind: Deployment
metadata:
  name: quingo-main-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quingo-main-service
  template:
    metadata:
      labels:
        app: quingo-main-service
    spec:
      containers:
        - name: main-service-container
          image: artem5252/quingo-main-service:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: DB_NAME
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: DB_HOST
          ports:
            - containerPort: 8080